// <auto-generated />
using System;
using DmarcAnalyzer.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DmarcAnalyzer.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DmarcAnalyzerDbContext))]
    partial class DmarcAnalyzerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.DkimAuthResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DmarcRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HumanResult")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<string>("Selector")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DmarcRecordId");

                    b.ToTable("DkimAuthResults", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.DkimSelectorCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CheckedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DkimAuthResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RawTxtRecord")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("StaleFlag")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DkimAuthResultId")
                        .IsUnique();

                    b.ToTable("DkimSelectorChecks", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.DmarcAggregateReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateRangeBeginUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRangeEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ExtraContactInfo")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("GraphMessageId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("MailboxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrgName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PolicyAdkim")
                        .HasColumnType("int");

                    b.Property<int>("PolicyAspf")
                        .HasColumnType("int");

                    b.Property<string>("PolicyFo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PolicyP")
                        .HasColumnType("int");

                    b.Property<int>("PolicyPct")
                        .HasColumnType("int");

                    b.Property<string>("PolicyPublishedDomain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PolicySp")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("MailboxId");

                    b.HasIndex("DomainId", "DateRangeBeginUtc");

                    b.ToTable("AggregateReports", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.DmarcRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("EnvelopeFrom")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EnvelopeTo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HeaderFrom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PolicyEvaluatedDisposition")
                        .HasColumnType("int");

                    b.Property<int>("PolicyEvaluatedDkim")
                        .HasColumnType("int");

                    b.Property<int>("PolicyEvaluatedSpf")
                        .HasColumnType("int");

                    b.Property<string>("PolicyOverrideReasons")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SourceIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("Id");

                    b.HasIndex("AggregateReportId");

                    b.HasIndex("SourceIp");

                    b.ToTable("Records", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.Domain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DomainName")
                        .IsUnique();

                    b.ToTable("Domains", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.DomainMailbox", b =>
                {
                    b.Property<Guid>("DomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MailboxId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DomainId", "MailboxId");

                    b.HasIndex("MailboxId");

                    b.ToTable("DomainMailboxes", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.GraphConnectionSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientSecretKeyVaultName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ConfiguredUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastValidatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastValidationError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("LastValidationSucceeded")
                        .HasColumnType("bit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("GraphConnectionSettings", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.Mailbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeltaLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastPollError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("LastPollStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastPolledUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MailFolder")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MailboxUpn")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.HasKey("Id");

                    b.HasIndex("MailboxUpn")
                        .IsUnique();

                    b.ToTable("Mailboxes", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.ProcessedMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttachmentType")
                        .HasColumnType("int");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("GraphMessageId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("MailboxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ProcessedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MailboxId", "GraphMessageId")
                        .IsUnique();

                    b.ToTable("ProcessedMessages", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.RetentionSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("LastPurgeRowsDeleted")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastPurgeRunUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RetentionSettings", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.SpfAuthResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DmarcRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DmarcRecordId");

                    b.ToTable("SpfAuthResults", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.SpfEvaluationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DiscrepancyFlag")
                        .HasColumnType("bit");

                    b.Property<string>("DiscrepancyNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("DmarcRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EvaluatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LiveSpfRecordText")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("LookupCount")
                        .HasColumnType("int");

                    b.Property<string>("MatchedMechanism")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RecomputedResult")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DmarcRecordId")
                        .IsUnique();

                    b.ToTable("SpfEvaluationResults", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.VerifiedSenderOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OrgNamePattern")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SourceIpCidr")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.ToTable("VerifiedSenderOverrides", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.DkimAuthResult", b =>
                {
                    b.HasOne("DmarcAnalyzer.Core.Entities.DmarcRecord", "DmarcRecord")
                        .WithMany("DkimAuthResults")
                        .HasForeignKey("DmarcRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DmarcRecord");
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.DkimSelectorCheck", b =>
                {
                    b.HasOne("DmarcAnalyzer.Core.Entities.DkimAuthResult", "DkimAuthResult")
                        .WithOne("SelectorCheck")
                        .HasForeignKey("DmarcAnalyzer.Core.Entities.DkimSelectorCheck", "DkimAuthResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DkimAuthResult");
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.DmarcAggregateReport", b =>
                {
                    b.HasOne("DmarcAnalyzer.Core.Entities.Domain", "Domain")
                        .WithMany("AggregateReports")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DmarcAnalyzer.Core.Entities.Mailbox", "Mailbox")
                        .WithMany()
                        .HasForeignKey("MailboxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Domain");

                    b.Navigation("Mailbox");
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.DmarcRecord", b =>
                {
                    b.HasOne("DmarcAnalyzer.Core.Entities.DmarcAggregateReport", "AggregateReport")
                        .WithMany("Records")
                        .HasForeignKey("AggregateReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AggregateReport");
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.DomainMailbox", b =>
                {
                    b.HasOne("DmarcAnalyzer.Core.Entities.Domain", "Domain")
                        .WithMany("DomainMailboxes")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DmarcAnalyzer.Core.Entities.Mailbox", "Mailbox")
                        .WithMany("DomainMailboxes")
                        .HasForeignKey("MailboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");

                    b.Navigation("Mailbox");
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.ProcessedMessage", b =>
                {
                    b.HasOne("DmarcAnalyzer.Core.Entities.Mailbox", "Mailbox")
                        .WithMany()
                        .HasForeignKey("MailboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mailbox");
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.SpfAuthResult", b =>
                {
                    b.HasOne("DmarcAnalyzer.Core.Entities.DmarcRecord", "DmarcRecord")
                        .WithMany("SpfAuthResults")
                        .HasForeignKey("DmarcRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DmarcRecord");
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.SpfEvaluationResult", b =>
                {
                    b.HasOne("DmarcAnalyzer.Core.Entities.DmarcRecord", "DmarcRecord")
                        .WithOne("SpfEvaluation")
                        .HasForeignKey("DmarcAnalyzer.Core.Entities.SpfEvaluationResult", "DmarcRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DmarcRecord");
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.VerifiedSenderOverride", b =>
                {
                    b.HasOne("DmarcAnalyzer.Core.Entities.Domain", "Domain")
                        .WithMany("VerifiedSenderOverrides")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.DkimAuthResult", b =>
                {
                    b.Navigation("SelectorCheck");
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.DmarcAggregateReport", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.DmarcRecord", b =>
                {
                    b.Navigation("DkimAuthResults");

                    b.Navigation("SpfAuthResults");

                    b.Navigation("SpfEvaluation");
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.Domain", b =>
                {
                    b.Navigation("AggregateReports");

                    b.Navigation("DomainMailboxes");

                    b.Navigation("VerifiedSenderOverrides");
                });

            modelBuilder.Entity("DmarcAnalyzer.Core.Entities.Mailbox", b =>
                {
                    b.Navigation("DomainMailboxes");
                });
#pragma warning restore 612, 618
        }
    }
}
